<?php
// Italian lists, tuned on a real 777-post site: they caught every malformed anchor in the
// review sample and none of the good ones. 'dato' is left out of the verbs on purpose,
// because on a real site it is nearly always a noun (dato personale, dato misurato).
return array(
	'stop'          => "il lo la i gli le un uno una di a da in con su per tra fra e o ma che chi cui non piu meno come dove quando perche se anche ancora gia poi solo molto tutto tutti tutte questo questa questi queste quello quella quelli quelle mio mia miei mie tuo tua suo sua suoi sue dopo nostro vostra loro essere avere fare dire potere volere dovere sapere stare dare vedere andare venire del della dello dei degli delle al allo alla ai agli alle dal dallo dalla dai dagli dalle nel nello nella nei negli nelle sul sullo sulla sui sugli sulle col coi si ci vi ne ha ho hai hanno era sono sia qui qua ogni alcuni alcune altro altra altri altre stesso stessa più già può così perché",
	'edge'          => "di a da in con su per tra fra e o ma che il lo la i gli le un uno una del della dei delle al alla ai alle dal dalla nel nella sul sulla dietro dentro sotto sopra",
	'interrogative' => "cosa come quando perche perché quale quali chi dove quanto quanta quanti quante ecco ora adesso poi",
	'article'       => "il lo la i gli le un uno una l",
	'verb'          => "ha hai hanno ho abbiamo avete era erano sono sei siamo siete stato stata fu furono saranno fa fanno faranno va vanno possono deve devono vuole vogliono dice dicono arriva arrivano diventa diventano cambia cambiano compra comprano porta portano mette mettono toglie tolgono usa usano apre aprono chiude chiudono lancia lanciano serve servono acquisito comprato lanciato aperto chiuso tolto messo fatto detto visto preso riscritto generato spiegato scelto trovato perso vinto smette smettono è può sarà farà andrà potrà dovrà vorrà dirà arriverà diventerà cambierà comprerà porterà metterà userà interessa interessano riguarda riguardano significa significano rappresenta rappresentano dimostra dimostrano conferma confermano permette permettono consente consentono ricorda ricordano racconta raccontano spiega spiegano mostra mostrano funziona funzionano sembra sembrano resta restano riesce riescono trova trovano parla parlano vede vedono sa sanno sta stanno vuoi puoi devi sai vai stai vedi trovi usi scopri scoprirai imparerai potrai dovrai vorrai saprai avrai sarai farai vedrai troverai",
	'participle'    => "ato ata ati ate ito ita iti ite uto uta uti ute",
);
